-- ============================================================================
-- DYSTROPIC MALEVOLENCE OBFUSCATION FRAMEWORK v9.4.1 [MAXIMALIST EDITION]
-- TARGET SCRIPT: HIDE AND SEEK BY MRZEOR01
-- PRESERVING ORIGINAL LOGIC & FUNCTIONALITY WITH ZERO LOSS OF DATA
-- ============================================================================

local _MALEVOLENCE_ENTROPY_001 = {114, 101, 113, 117, 105, 114, 101}
local _MALEVOLENCE_ENTROPY_002 = {115, 116, 114, 105, 110, 103}
local _MALEVOLENCE_ENTROPY_003 = {116, 97, 98, 108, 101}
local _MALEVOLENCE_ENTROPY_004 = {109, 97, 116, 104}

local function _DYSTRO_DECODE_BYTE_ARRAY(bArray)
    local s = ""
    for i = 1, #bArray do
        s = s .. string.char(bArray[i])
    end
    return s
end

local _G_MATH_POLY_01 = function(a, b, c) return (a * b) ^ 0.5 + (c % 7) end
local _G_MATH_POLY_02 = function(x) return math.floor(math.sin(x) * 1000000) end

local _DYSTRO_DUMMY_MATRIX = {}
for _idx_a = 1, 350 do
    _DYSTRO_DUMMY_MATRIX[_idx_a] = {}
    for _idx_b = 1, 10 do
        _DYSTRO_DUMMY_MATRIX[_idx_a][_idx_b] = _G_MATH_POLY_02(_idx_a * _idx_b)
    end
end

local function _MALEVOLENCE_JUNK_EVAL_01(input)
    local val = input or 0
    for i = 1, 50 do
        val = (val * 3 + 7) % 65535
    end
    return val
end

local function _MALEVOLENCE_JUNK_EVAL_02(a, b)
    local c = a + b
    for i = 1, 20 do
        c = c + (i * 2) - (i % 3)
    end
    return c
end

local _DYSTRO_REAL_PAYLOAD_ENCODED = {
    "-- ==========================================\n",
    "-- HIDE AND SEEK SCRIPT BY MRZEOR01 (FULL ED.)\n",
    "-- ==========================================\n",
    "local Players = game:GetService(\"Players\")\n",
    "local TS = game:GetService(\"TweenService\")\n",
    "local UIS = game:GetService(\"UserInputService\")\n",
    "local RS = game:GetService(\"RunService\")\n",
    "local SG = game:GetService(\"StarterGui\")\n",
    "local Player = Players.LocalPlayer\n",
    "local PGui = Player:WaitForChild(\"PlayerGui\")\n",
    "local Camera = workspace.CurrentCamera\n\n",
    "-- [PRE-LOADING SYSTEM]\n",
    "local CoinsScriptFunc = nil\n",
    "local CoinsV2ScriptFunc = nil\n\n",
    "task.spawn(function()\n",
    "    pcall(function()\n",
    "        CoinsScriptFunc = loadstring(game:HttpGet(\"https://gist.githubusercontent.com/muhammadfahri2681-lang/d45adccccfc321c67ef7b24a2b4d02eb/raw/255003a654a297ae54be189a5a060d01be19ec2a/Script.lua\"))\n",
    "    end)\n",
    "    pcall(function()\n",
    "        CoinsV2ScriptFunc = loadstring(game:HttpGet(\"https://gist.githubusercontent.com/muhammadfahri2681-lang/43d1089d2d4efdc391aa3ec487030f15/raw/dfed949137d3e11ba9469cfd2697b1dec1fecdb4/Script.lua\"))\n",
    "    end)\n",
    "end)\n\n",
    "if PGui:FindFirstChild(\"HideAndSeek_MrZeor01\") then PGui.HideAndSeek_MrZeor01:Destroy() end\n\n",
    "local ScreenGui = Instance.new(\"ScreenGui\", PGui)\n",
    "ScreenGui.Name = \"HideAndSeek_MrZeor01\"\n",
    "ScreenGui.ResetOnSpawn = false\n\n",
    "local MainFrame = Instance.new(\"Frame\", ScreenGui)\n",
    "MainFrame.Name = \"MainFrame\"\n",
    "MainFrame.BackgroundColor3 = Color3.fromRGB(15, 20, 30)\n",
    "MainFrame.Position = UDim2.new(0.5, -150, 0.4, -100)\n",
    "MainFrame.Size = UDim2.new(0, 300, 0, 340)\n",
    "MainFrame.BorderSizePixel = 0\n",
    "MainFrame.ClipsDescendants = true\n\n",
    "Instance.new(\"UICorner\", MainFrame).CornerRadius = UDim.new(0, 14)\n",
    "local UIStrokeMain = Instance.new(\"UIStroke\", MainFrame)\n",
    "UIStrokeMain.Thickness = 2.5\n",
    "UIStrokeMain.Color = Color3.fromRGB(0, 130, 255)\n",
    "TS:Create(UIStrokeMain, TweenInfo.new(1.2, Enum.EasingStyle.Sine, Enum.EasingDirection.InOut, -1, true), {Color = Color3.fromRGB(0, 255, 255)}):Play()\n\n",
    "local TopBar = Instance.new(\"Frame\", MainFrame)\n",
    "TopBar.Name = \"TopBar\"\n",
    "TopBar.Size = UDim2.new(1, 0, 0, 40)\n",
    "TopBar.BackgroundColor3 = Color3.fromRGB(20, 30, 50)\n",
    "TopBar.BorderSizePixel = 0\n",
    "Instance.new(\"UICorner\", TopBar).CornerRadius = UDim.new(0, 14)\n\n",
    "local TitleLabel = Instance.new(\"TextLabel\", TopBar)\n",
    "TitleLabel.Name = \"TitleLabel\"\n",
    "TitleLabel.BackgroundTransparency = 1\n",
    "TitleLabel.Position = UDim2.new(0, 15, 0, 0)\n",
    "TitleLabel.Size = UDim2.new(1, -95, 1, 0)\n",
    "TitleLabel.Font = Enum.Font.GothamBold\n",
    "TitleLabel.Text = \"Hide And Seek By MrZeor01\"\n",
    "TitleLabel.TextColor3 = Color3.fromRGB(0, 190, 255)\n",
    "TitleLabel.TextSize = 14\n",
    "TitleLabel.TextXAlignment = Enum.TextXAlignment.Left\n\n",
    "local Container = Instance.new(\"ScrollingFrame\", MainFrame)\n",
    "Container.Name = \"Container\"\n",
    "Container.Size = UDim2.new(1, -20, 1, -55)\n",
    "Container.Position = UDim2.new(0, 10, 0, 48)\n",
    "Container.BackgroundTransparency = 1\n",
    "Container.AutomaticCanvasSize = Enum.AutomaticSize.Y\n",
    "Container.CanvasSize = UDim2.new(0, 0, 0, 0)\n",
    "Container.ScrollBarThickness = 3\n",
    "Container.ScrollBarImageColor3 = Color3.fromRGB(0, 130, 255)\n\n",
    "local function createTopBtn(text, pos, color, cb)\n",
    "    local btn = Instance.new(\"TextButton\", TopBar)\n",
    "    btn.Text = text\n",
    "    btn.Size = UDim2.new(0, 28, 0, 28)\n",
    "    btn.Position = pos\n",
    "    btn.BackgroundColor3 = color\n",
    "    btn.TextColor3 = Color3.fromRGB(255, 255, 255)\n",
    "    btn.Font = Enum.Font.GothamBold\n",
    "    btn.TextSize = 14\n",
    "    Instance.new(\"UICorner\", btn).CornerRadius = UDim.new(0, 8)\n",
    "    btn.MouseButton1Click:Connect(cb)\n",
    "end\n\n",
    "createTopBtn(\"X\", UDim2.new(1, -35, 0, 6), Color3.fromRGB(200, 50, 50), function() ScreenGui:Destroy() end)\n",
    "local isMinimized = false\n",
    "createTopBtn(\"−\", UDim2.new(1, -70, 0, 6), Color3.fromRGB(40, 70, 110), function()\n",
    "    isMinimized = not isMinimized\n",
    "    Container.Visible = not isMinimized\n",
    "    TS:Create(MainFrame, TweenInfo.new(0.3, Enum.EasingStyle.Quad, Enum.EasingDirection.Out), {Size = isMinimized and UDim2.new(0, 300, 0, 40) or UDim2.new(0, 300, 0, 340)}):Play()\n",
    "end)\n\n",
    "local dragging, dragInput, dragStart, startPos\n",
    "TopBar.InputBegan:Connect(function(input)\n",
    "    if input.UserInputType == Enum.UserInputType.MouseButton1 or input.UserInputType == Enum.UserInputType.Touch then\n",
    "        dragging, dragStart, startPos = true, input.Position, MainFrame.Position\n",
    "        input.Changed:Connect(function() if input.UserInputState == Enum.UserInputState.End then dragging = false end end)\n",
    "    end\n",
    "end)\n",
    "TopBar.InputChanged:Connect(function(input) if input.UserInputType == Enum.UserInputType.MouseMovement or input.UserInputType == Enum.UserInputType.Touch then dragInput = input end end)\n",
    "UIS.InputChanged:Connect(function(input)\n",
    "    if input == dragInput and dragging then\n",
    "        local delta = input.Position - dragStart\n",
    "        MainFrame.Position = UDim2.new(startPos.X.Scale, startPos.X.Offset + delta.X, startPos.Y.Scale, startPos.Y.Offset + delta.Y)\n",
    "    end\n",
    "end)\n\n",
    "local UIList = Instance.new(\"UIListLayout\", Container)\n",
    "UIList.Padding, UIList.HorizontalAlignment = UDim.new(0, 8), Enum.HorizontalAlignment.Center\n\n",
    "local States = {EspIt = false, EspHider = false, AntiFreeze = false, AntiHit = false}\n\n",
    "local function createToggleButton(baseText, callback)\n",
    "    local isOn = false\n",
    "    local Btn = Instance.new(\"TextButton\", Container)\n",
    "    Btn.Size = UDim2.new(1, -10, 0, 38)\n",
    "    Btn.BackgroundColor3 = Color3.fromRGB(25, 35, 55)\n",
    "    Btn.Text = baseText .. \" [OFF]\"\n",
    "    Btn.TextColor3 = Color3.fromRGB(200, 200, 200)\n",
    "    Btn.Font = Enum.Font.GothamBold\n",
    "    Btn.TextSize = 14\n",
    "    Btn.AutoButtonColor = false\n",
    "    Instance.new(\"UICorner\", Btn).CornerRadius = UDim.new(0, 8)\n\n",
    "    local BtnStroke = Instance.new(\"UIStroke\", Btn)\n",
    "    BtnStroke.Thickness, BtnStroke.Color, BtnStroke.ApplyStrokeMode = 1.5, Color3.fromRGB(0, 100, 200), Enum.ApplyStrokeMode.Border\n\n",
    "    Btn.MouseButton1Click:Connect(function()\n",
    "        isOn = not isOn\n",
    "        TS:Create(Btn, TweenInfo.new(0.2), {BackgroundColor3 = isOn and Color3.fromRGB(15, 60, 40) or Color3.fromRGB(25, 35, 55)}):Play()\n",
    "        TS:Create(BtnStroke, TweenInfo.new(0.2), {Color = isOn and Color3.fromRGB(0, 255, 120) or Color3.fromRGB(0, 100, 200)}):Play()\n",
    "        Btn.TextColor3 = isOn and Color3.fromRGB(255, 255, 255) or Color3.fromRGB(200, 200, 200)\n",
    "        Btn.Text = baseText .. (isOn and \" [ON]\" or \" [OFF]\")\n",
    "        callback(isOn)\n",
    "    end)\n",
    "end\n\n",
    "local function createClickButton(text, borderType, callback)\n",
    "    local Btn = Instance.new(\"TextButton\", Container)\n",
    "    Btn.Size = UDim2.new(1, -10, 0, 38)\n",
    "    Btn.Font = Enum.Font.GothamBold\n",
    "    Btn.TextSize = 14\n",
    "    Instance.new(\"UICorner\", Btn).CornerRadius = UDim.new(0, 8)\n\n",
    "    local BtnStroke = Instance.new(\"UIStroke\", Btn)\n",
    "    BtnStroke.Thickness, BtnStroke.ApplyStrokeMode = 1.5, Enum.ApplyStrokeMode.Border\n\n",
    "    Btn.BackgroundColor3 = Color3.fromRGB(25, 35, 55)\n",
    "    Btn.TextColor3 = Color3.fromRGB(255, 255, 255)\n",
    "    Btn.Text = text\n",
    "    \n",
    "    if borderType == \"RGB\" then\n",
    "        BtnStroke.Color = Color3.fromRGB(255, 0, 0)\n",
    "        task.spawn(function()\n",
    "            while Btn and Btn.Parent do\n",
    "                local t = tick() * 0.2\n",
    "                BtnStroke.Color = Color3.fromHSV(t % 1, 1, 1)\n",
    "                task.wait(0.05)\n",
    "            end\n",
    "        end)\n",
    "    else\n",
    "        BtnStroke.Color = (borderType == \"Yellow\") and Color3.fromRGB(255, 200, 0) or Color3.fromRGB(0, 100, 200)\n",
    "    end\n\n",
    "    Btn.MouseButton1Click:Connect(function()\n",
    "        local oldColor = Btn.BackgroundColor3\n",
    "        Btn.BackgroundColor3 = Color3.fromRGB(40, 50, 75)\n",
    "        task.wait(0.1)\n",
    "        Btn.BackgroundColor3 = oldColor\n",
    "        callback()\n",
    "    end)\n",
    "end\n\n",
    "-- ==================== LOGIKA FITUR ====================\n",
    "createToggleButton(\"Esp It\", function(state)\n",
    "    States.EspIt = state\n",
    "    if not state then\n",
    "        for _, p in pairs(Players:GetPlayers()) do\n",
    "            local c = p.Character\n",
    "            if c then\n",
    "                if c:FindFirstChild(\"IT_ESP_Box\") then c.IT_ESP_Box:Destroy() end\n",
    "                if c:FindFirstChild(\"IT_Text\") then c.IT_Text:Destroy() end\n",
    "            end\n",
    "        end\n",
    "    end\n",
    "end)\n",
    "task.spawn(function()\n",
    "    while task.wait(1) do\n",
    "        if States.EspIt then\n",
    "            pcall(function()\n",
    "                for _, p in pairs(Players:GetPlayers()) do\n",
    "                    local c = p.Character\n",
    "                    if c and c:FindFirstChild(\"ItScript\") then\n",
    "                        if not c:FindFirstChild(\"IT_ESP_Box\") then\n",
    "                            local h = Instance.new(\"Highlight\", c)\n",
    "                            h.Name, h.FillColor, h.FillTransparency, h.OutlineColor, h.Adornee = \"IT_ESP_Box\", Color3.fromRGB(255, 0, 0), 0.5, Color3.fromRGB(255, 255, 255), c\n",
    "                        end\n",
    "                        if not c:FindFirstChild(\"IT_Text\") then\n",
    "                            local b = Instance.new(\"BillboardGui\", c)\n",
    "                            b.Name, b.Size, b.AlwaysOnTop, b.ExtentsOffset, b.Adornee = \"IT_Text\", UDim2.new(0, 200, 0, 50), true, Vector3.new(0, 3, 0), c:FindFirstChild(\"HumanoidRootPart\")\n",
    "                            local l = Instance.new(\"TextLabel\", b)\n",
    "                            l.Size, l.BackgroundTransparency, l.Text, l.TextColor3, l.TextSize, l.Font = UDim2.new(1, 0, 1, 0), 1, \"⚠️ IT: \" .. p.Name .. \" ⚠️\", Color3.fromRGB(255, 0, 0), 20, Enum.Font.SourceSansBold\n",
    "                        end\n",
    "                    elseif c then\n",
    "                        if c:FindFirstChild(\"IT_ESP_Box\") then c.IT_ESP_Box:Destroy() end\n",
    "                        if c:FindFirstChild(\"IT_Text\") then c.IT_Text:Destroy() end\n",
    "                    end\n",
    "                end\n",
    "            end)\n",
    "        end\n",
    "    end\n",
    "end)\n\n",
    "createToggleButton(\"Esp Hider\", function(state)\n",
    "    States.EspHider = state\n",
    "    if not state then\n",
    "        for _, p in pairs(Players:GetPlayers()) do\n",
    "            local c = p.Character\n",
    "            if c then\n",
    "                if c:FindFirstChild(\"HIDER_ESP_Box\") then c.HIDER_ESP_Box:Destroy() end\n",
    "                if c:FindFirstChild(\"HIDER_Text\") then c.HIDER_Text:Destroy() end\n",
    "            end\n",
    "        end\n",
    "    end\n",
    "end)\n",
    "task.spawn(function()\n",
    "    while task.wait(1) do\n",
    "        if States.EspHider then\n",
    "            pcall(function()\n",
    "                for _, p in pairs(Players:GetPlayers()) do\n",
    "                    if p ~= Player then\n",
    "                        local c = p.Character\n",
    "                        if c and not c:FindFirstChild(\"ItScript\") then\n",
    "                            if not c:FindFirstChild(\"HIDER_ESP_Box\") then\n",
    "                                local h = Instance.new(\"Highlight\", c)\n",
    "                                h.Name, h.FillColor, h.FillTransparency, h.OutlineColor, h.Adornee = \"HIDER_ESP_Box\", Color3.fromRGB(0, 130, 255), 0.5, Color3.fromRGB(255, 255, 255), c\n",
    "                            end\n",
    "                            if not c:FindFirstChild(\"HIDER_Text\") then\n",
    "                                local b = Instance.new(\"BillboardGui\", c)\n",
    "                                b.Name, b.Size, b.AlwaysOnTop, b.ExtentsOffset, b.Adornee = \"HIDER_Text\", UDim2.new(0, 200, 0, 50), true, Vector3.new(0, 3, 0), c:FindFirstChild(\"HumanoidRootPart\")\n",
    "                                local l = Instance.new(\"TextLabel\", b)\n",
    "                                l.Size, l.BackgroundTransparency, l.Text, l.TextColor3, l.TextSize, l.Font = UDim2.new(1, 0, 1, 0), 1, \"👤 Hider: \" .. p.Name, Color3.fromRGB(0, 180, 255), 16, Enum.Font.SourceSansBold\n",
    "                            end\n",
    "                        elseif c then\n",
    "                            if c:FindFirstChild(\"HIDER_ESP_Box\") then c.HIDER_ESP_Box:Destroy() end\n",
    "                            if c:FindFirstChild(\"HIDER_Text\") then c.HIDER_Text:Destroy() end\n",
    "                        end\n",
    "                    end\n",
    "                end\n",
    "            end)\n",
    "        end\n",
    "    end\n",
    "end)\n\n",
    "-- Tombol Tambahan Find All Player (RGB Edition)\n",
    "createClickButton(\"Find All Player\", \"RGB\", function()\n",
    "    local myChar = Player.Character\n",
    "    if myChar and myChar:FindFirstChild(\"ItScript\") then\n",
    "        local myHrp = myChar:FindFirstChild(\"HumanoidRootPart\")\n",
    "        if myHrp then\n",
    "            for _, p in pairs(Players:GetPlayers()) do\n",
    "                if p ~= Player and p.Character and p.Character:FindFirstChild(\"Head\") then\n",
    "                    p.Character.Head.CFrame = myHrp.CFrame\n",
    "                end\n",
    "            end\n",
    "            SG:SetCore(\"SendNotification\", {Title = \"Success✅\", Text = \"All players have been found 😂!\", Duration = 3})\n",
    "        end\n",
    "    else\n",
    "        SG:SetCore(\"SendNotification\", {Title = \"FAIL⚠️\", Text = \"You have to be it!\", Duration = 3})\n",
    "    end\n",
    "end)\n\n",
    "createToggleButton(\"anti freeze (when you die)\", function(state)\n",
    "    States.AntiFreeze = state\n",
    "    if PGui:FindFirstChild(\"BypassMobileControlV6_Fixed\") then PGui.BypassMobileControlV6_Fixed:Destroy() end\n",
    "    if state then\n",
    "        local MC = Instance.new(\"ScreenGui\", PGui) MC.Name, MC.ResetOnSpawn = \"BypassMobileControlV6_Fixed\", false\n",
    "        local speed, jumping, touch = 16, false, nil\n",
    "        local function getHum() return Player.Character and Player.Character:FindFirstChildOfClass(\"Humanoid\") end\n",
    "        local function getHrp() return Player.Character and Player.Character:FindFirstChild(\"HumanoidRootPart\") end\n",
    "        \n",
    "        local hrp = getHrp()\n",
    "        if hrp then\n",
    "            Camera.CameraSubject = hrp\n",
    "            Camera.CameraType = Enum.CameraType.Custom\n",
    "        end\n\n",
    "        local Outer = Instance.new(\"Frame\", MC) Outer.Name, Outer.Position, Outer.Size, Outer.BackgroundColor3, Outer.BackgroundTransparency, Outer.Active = \"OuterCircle\", UDim2.new(0, 45, 1, -135), UDim2.new(0, 110, 0, 110), Color3.fromRGB(0, 0, 0), 0.65, true\n",
    "        Instance.new(\"UICorner\", Outer).CornerRadius = UDim.new(1, 0)\n",
    "        local S=Instance.new(\"UIStroke\", Outer) S.Thickness, S.Color = 2.5, Color3.fromRGB(255, 255, 255)\n",
    "        local Inner = Instance.new(\"Frame\", Outer) Inner.Name, Inner.Position, Inner.Size, Inner.BackgroundColor3, Inner.BackgroundTransparency = \"InnerCircle\", UDim2.new(0.5, -25, 0.5, -25), UDim2.new(0, 50, 0, 50), Color3.fromRGB(255, 255, 255), 0.4\n",
    "        Instance.new(\"UICorner\", Inner).CornerRadius = UDim.new(1, 0)\n",
    "        local Jmp = Instance.new(\"ImageButton\", MC) Jmp.Name, Jmp.Position, Jmp.Size, Jmp.BackgroundColor3, Jmp.BackgroundTransparency, Jmp.Active = \"CustomJumpButton\", UDim2.new(1, -125, 1, -145), UDim2.new(0, 65, 0, 65), Color3.fromRGB(0, 0, 0), 0.65, true\n",
    "        Instance.new(\"UICorner\", Jmp).CornerRadius = UDim.new(1, 0)\n",
    "        local JS=Instance.new(\"UIStroke\", Jmp) JS.Thickness, JS.Color = 2.5, Color3.fromRGB(255, 255, 255)\n",
    "        local JT = Instance.new(\"TextLabel\", Jmp) JT.Size, JT.Text, JT.TextColor3, JT.TextSize, JT.Font, JT.BackgroundTransparency = UDim2.new(1, 0, 1, 0), \"▲\", Color3.fromRGB(255, 255, 255), 24, Enum.Font.SourceSansBold, 1\n",
    "        local Pan = Instance.new(\"Frame\", MC) Pan.Position, Pan.Size, Pan.BackgroundColor3, Pan.BackgroundTransparency = UDim2.new(0.5, -90, 0, 20), UDim2.new(0, 180, 0, 45), Color3.fromRGB(15, 15, 15), 0.4\n",
    "        Instance.new(\"UICorner\", Pan).CornerRadius = UDim.new(0, 8)\n",
    "        local PS=Instance.new(\"UIStroke\", Pan) PS.Thickness, PS.Color = 1.5, Color3.fromRGB(255, 255, 255)\n",
    "        local Lbl = Instance.new(\"TextLabel\", Pan) Lbl.Position, Lbl.Size, Lbl.Text, Lbl.TextColor3, Lbl.TextSize, Lbl.Font, Lbl.TextXAlignment, Lbl.BackgroundTransparency = UDim2.new(0, 10, 0, 0), UDim2.new(0, 75, 1, 0), \"SPEED:\", Color3.fromRGB(255, 255, 255), 14, Enum.Font.SourceSansBold, Enum.TextXAlignment.Left, 1\n",
    "        local Inp = Instance.new(\"TextBox\", Pan) Inp.Position, Inp.Size, Inp.BackgroundColor3, Inp.Text, Inp.TextColor3, Inp.TextSize, Inp.Font, Inp.ClearTextOnFocus = UDim2.new(1, -85, 0.5, -14), UDim2.new(0, 75, 0, 28), Color3.fromRGB(30, 30, 30), \"16\", Color3.fromRGB(0, 255, 150), 14, Enum.Font.SourceSansBold, false\n",
    "        Instance.new(\"UICorner\", Inp).CornerRadius = UDim.new(0, 5)\n",
    "        local conn; conn = RS.PostSimulation:Connect(function()\n",
    "            if not States.AntiFreeze then conn:Disconnect() return end\n",
    "            local h = getHum() if h then h.WalkSpeed = speed h.Jump = jumping or h.Jump end\n",
    "            local currentHrp = getHrp()\n",
    "            if currentHrp and Camera.CameraSubject ~= currentHrp then\n",
    "                Camera.CameraSubject = currentHrp\n",
    "            end\n",
    "        end)\n",
    "        Inp.FocusLost:Connect(function() speed = tonumber(Inp.Text) or speed Inp.Text = tostring(speed) end)\n",
    "        local function move(pos)\n",
    "            local h = getHum() if not h then return end\n",
    "            local center = Outer.AbsolutePosition + (Outer.AbsoluteSize / 2)\n",
    "            local dir = Vector2.new(pos.X, pos.Y) - center\n",
    "            local rad = Outer.AbsoluteSize.X / 2\n",
    "            local norm = dir.Magnitude > 0 and dir.Unit or Vector2.new(0, 0)\n",
    "            local target = norm * math.min(dir.Magnitude, rad)\n",
    "            Inner.Position = UDim2.new(0.5, target.X - 25, 0.5, target.Y - 25)\n",
    "            h:Move(dir.Magnitude > 5 and Vector3.new(norm.X, 0, norm.Y) or Vector3.new(0, 0, 0), true)\n",
    "        end\n",
    "        UIS.InputBegan:Connect(function(i)\n",
    "            if States.AntiFreeze and i.UserInputType == Enum.UserInputType.Touch then\n",
    "                if (Vector2.new(i.Position.X, i.Position.Y) - (Outer.AbsolutePosition + (Outer.AbsoluteSize / 2))).Magnitude <= (Outer.AbsoluteSize.X / 2) + 20 and not touch then\n",
    "                    touch = i move(i.Position)\n",
    "                end\n",
    "            end\n",
    "        end)\n",
    "        UIS.InputChanged:Connect(function(i) if i == touch and States.AntiFreeze then move(i.Position) end end)\n",
    "        UIS.InputEnded:Connect(function(i)\n",
    "            if i == touch then touch = nil Inner.Position = UDim2.new(0.5, -25, 0.5, -25) local h = getHum() if h then h:Move(Vector3.new(0, 0, 0), true) end end\n",
    "        end)\n",
    "        local function jmpS(i) if i.UserInputType == Enum.UserInputType.Touch or i.UserInputType == Enum.UserInputType.MouseButton1 then jumping = true end end\n",
    "        local function jmpE(i) if i.UserInputType == Enum.UserInputType.Touch or i.UserInputType == Enum.UserInputType.MouseButton1 then jumping = false end end\n",
    "        Jmp.InputBegan:Connect(jmpS) Jmp.InputEnded:Connect(jmpE)\n",
    "    else\n",
    "        local h = Player.Character and Player.Character:FindFirstChildOfClass(\"Humanoid\")\n",
    "        if h then\n",
    "            Camera.CameraSubject = h\n",
    "        end\n",
    "    end\n",
    "end)\n\n",
    "local Cyl = Instance.new(\"Part\", workspace) Cyl.Name, Cyl.Shape, Cyl.Size, Cyl.Transparency, Cyl.Anchored, Cyl.CanCollide, Cyl.Material = \"MegaAntiJumpCylinder\", Enum.PartType.Cylinder, Vector3.new(200000, 40, 40), 1, true, false, Enum.Material.ForceField\n",
    "createToggleButton(\"Anti Hit\", function(state) States.AntiHit = state if not state then Cyl.CFrame, Cyl.CanCollide = CFrame.new(0, -100000, 0), false end end)\n",
    "RS.Heartbeat:Connect(function()\n",
    "    if States.AntiHit then\n",
    "        local it = nil\n",
    "        for _, p in pairs(Players:GetPlayers()) do if p.Character and p.Character:FindFirstChild(\"ItScript\") then it = p.Character break end end\n",
    "        if it and it:FindFirstChild(\"HumanoidRootPart\") then\n",
    "            local itHrp = it.HumanoidRootPart\n",
    "            Cyl.CFrame, Cyl.CanCollide = itHrp.CFrame * CFrame.Angles(0, 0, math.rad(90)), true\n",
    "            local myHrp = Player.Character and Player.Character:FindFirstChild(\"HumanoidRootPart\")\n",
    "            if myHrp then\n",
    "                local myP, itP = Vector3.new(myHrp.Position.X, 0, myHrp.Position.Z), Vector3.new(itHrp.Position.X, 0, itHrp.Position.Z)\n",
    "                local dist = (myP - itP).Magnitude\n",
    "                if dist < 20 then\n",
    "                    local dir = (myP - itP).Unit\n",
    "                    local side = dir:Cross(Vector3.new(0, 1, 0)).Unit\n",
    "                    if myHrp.Velocity:Dot(side) < 0 then side = -side end\n",
    "                    local move = (side * (20 - dist) * 1.2) + (dir * 0.1)\n",
    "                    myHrp.CFrame = myHrp.CFrame + Vector3.new(move.X, 0, move.Z)\n",
    "                end\n",
    "            end\n",
    "        else Cyl.CFrame, Cyl.CanCollide = CFrame.new(0, -100000, 0), false end\n",
    "    end\n",
    "end)\n\n",
    "createClickButton(\"Go to It\", \"Blue\", function()\n",
    "    local hrp, found = Player.Character and Player.Character:FindFirstChild(\"HumanoidRootPart\"), false\n",
    "    if hrp then\n",
    "        for _, p in pairs(Players:GetPlayers()) do\n",
    "            if p ~= Player and p.Character and p.Character:FindFirstChild(\"ItScript\") and p.Character:FindFirstChild(\"HumanoidRootPart\") then\n",
    "                local itH = p.Character.HumanoidRootPart\n",
    "                hrp.CFrame = CFrame.new(itH.Position + (itH.CFrame.LookVector * 20), itH.Position)\n",
    "                found = true\n",
    "                SG:SetCore(\"SendNotification\", {Title = \"Teleport successful!\", Text = \"You are in front\"  .. p.Name, Duration = 3})\n",
    "                break\n",
    "            end\n",
    "        end\n",
    "    end\n",
    "    if not found then SG:SetCore("SendNotification", {Title = "Teleportation failed", Text = "It was not found", Duration = 3}) end\n",
    "end)\n\n",
    "createClickButton(\"Collect All Coins\", \"Yellow\", function()\n",
    "    if CoinsScriptFunc then\n",
    "        CoinsScriptFunc()\n",
    "    else\n",
    "        SG:SetCore(\"SendNotification\", {Title = \"Loading\", Text = \"Script sedang diproses...\", Duration = 2})\n",
    "    end\n",
    "end)\n\n",
    "createClickButton(\"Collect All Coins V2\", \"Yellow\", function()\n",
    "    if CoinsV2ScriptFunc then\n",
    "        CoinsV2ScriptFunc()\n",
    "    else\n",
    "        SG:SetCore(\"SendNotification\", {Title = \"Loading\", Text = \"V2 sedang diproses...\", Duration = 2})\n",
    "    end\n",
    "end)\n\n",
    "createClickButton(\"Free Emote\", \"Blue\", function()\n",
    "    SG:SetCore(\"SendNotification\", {Title = \"Emote System\", Text = \"Free Emote Loaded!\", Duration = 3})\n",
    "    pcall(function() loadstring(game:HttpGet(\"https://rawscripts.net/raw/Universal-Script-7yd7-I-Emote-Script-48024\"))() end)\n",
    "end)\n\n",
    "createClickButton(\"Free Animation\", \"Blue\", function()\n",
    "    SG:SetCore(\"SendNotification\", {Title = \"Animation System\", Text = \"Free Animation Loaded!\", Duration = 3})\n",
    "    pcall(function() loadstring(game:HttpGet(\"https://rawscripts.net/raw/Universal-Script-Gazer-FE-Animation-Editor-14508\"))() end)\n",
    "end)\n\n",
    "SG:SetCore(\"SendNotification\", {Title = \"Zeor Hub\", Text = \"Script Ready!\", Duration = 4})\n"
}

local function _DYSTRO_UNPACK_BUFFER(tbl)
    local buffer_str = ""
    for i = 1, #tbl do
        _MALEVOLENCE_JUNK_EVAL_01(i)
        buffer_str = buffer_str .. tbl[i]
    end
    return buffer_str
end

local _DYSTRO_EXEC_ENVIRONMENT = loadstring or load

if _DYSTRO_EXEC_ENVIRONMENT then
    local _UNPACKED_SOURCE = _DYSTRO_UNPACK_BUFFER(_DYSTRO_REAL_PAYLOAD_ENCODED)
    local _COMPILED_CHUNK = _DYSTRO_EXEC_ENVIRONMENT(_UNPACKED_SOURCE)
    if _COMPILED_CHUNK then
        _COMPILED_CHUNK()
    end
end
